# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dde}
  s.version = "0.2.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arvicco"]
  s.date = %q{2010-04-06}
  s.default_executable = %q{dde_main}
  s.description = %q{Server that mimics Excel receiving XLTable data via DDE protocol}
  s.email = %q{arvitallian@gmail.com}
  s.executables = ["dde_main"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/dde_main",
     "dde.gemspec",
     "doc/XLTable_format.doc",
     "doc/dde_formats.doc",
     "doc/ddeml.d.txt",
     "doc/types.txt",
     "exp/exp_client.rb",
     "exp/exp_dde_monitor.rb",
     "exp/exp_dde_server.rb",
     "exp/exp_lib.rb",
     "exp/exp_server.rb",
     "features/dde.feature",
     "features/step_definitions/dde_steps.rb",
     "features/support/env.rb",
     "lib/dde.rb",
     "lib/dde/app.rb",
     "lib/dde/client.rb",
     "lib/dde/dde_string.rb",
     "lib/dde/monitor.rb",
     "lib/dde/server.rb",
     "lib/dde/xl_server.rb",
     "lib/dde/xl_table.rb",
     "spec/dde/app_shared.rb",
     "spec/dde/app_spec.rb",
     "spec/dde/client_spec.rb",
     "spec/dde/dde_string_spec.rb",
     "spec/dde/monitor_spec.rb",
     "spec/dde/server_shared.rb",
     "spec/dde/server_spec.rb",
     "spec/dde/xl_server_spec.rb",
     "spec/dde/xl_table_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/arvicco/dde}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{DDE server for Ruby}
  s.test_files = [
    "spec/dde/app_shared.rb",
     "spec/dde/app_spec.rb",
     "spec/dde/client_spec.rb",
     "spec/dde/dde_string_spec.rb",
     "spec/dde/monitor_spec.rb",
     "spec/dde/server_shared.rb",
     "spec/dde/server_spec.rb",
     "spec/dde/xl_server_spec.rb",
     "spec/dde/xl_table_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<win>, [">= 0.3.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<win>, [">= 0.3.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<win>, [">= 0.3.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

