# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dde}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arvicco"]
  s.date = %q{2010-02-26}
  s.default_executable = %q{dde_main}
  s.description = %q{Server that mimics Excel receiving XLTable data via DDE protocol}
  s.email = %q{arvitallian@gmail.com}
  s.executables = ["dde_main"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/dde_main",
     "dde.gemspec",
     "doc/XLTable_format.doc",
     "doc/dde_formats.doc",
     "doc/ddeml.d.txt",
     "doc/types.txt",
     "features/dde.feature",
     "features/step_definitions/dde_steps.rb",
     "features/support/env.rb",
     "lib/dde.rb",
     "lib/dde/app.rb",
     "lib/dde/client.rb",
     "lib/dde/dde_string.rb",
     "lib/dde/monitor.rb",
     "lib/dde/server.rb",
     "lib/dde/xl_server.rb",
     "lib/dde/xl_table.rb",
     "misc/QuickAutostart.vbs",
     "misc/alioshinov/builds/DDE_Server2.exe",
     "misc/alioshinov/builds/DDE_server.exe",
     "misc/alioshinov/builds/DDE_server1.exe",
     "misc/alioshinov/prj/DDE_server/DDE_server.ncb",
     "misc/alioshinov/prj/DDE_server/DDE_server.sln",
     "misc/alioshinov/prj/DDE_server/DDE_server.suo",
     "misc/alioshinov/prj/DDE_server/DDE_server/DDE_server.vcproj",
     "misc/alioshinov/prj/DDE_server/DDE_server/DDE_server.vcproj.HASTER.Alioshinov.user",
     "misc/alioshinov/prj/DDE_server/DDE_server/DDE_server.vcproj.NOTEBOOK.Haster.user",
     "misc/alioshinov/prj/DDE_server/DDE_server/XlTable.cpp",
     "misc/alioshinov/prj/DDE_server/DDE_server/XlTable.h",
     "misc/alioshinov/prj/DDE_server/DDE_server/command_line_parser.cpp",
     "misc/alioshinov/prj/DDE_server/DDE_server/command_line_parser.h",
     "misc/alioshinov/prj/DDE_server/DDE_server/dde_server.cpp",
     "misc/alioshinov/prj/DDE_server/DDE_server/dde_server.h",
     "misc/alioshinov/prj/DDE_server/DDE_server/main.cpp",
     "misc/alioshinov/prj/dde/DDE_server.doc",
     "misc/alioshinov/prj/dde/dde.ncb",
     "misc/alioshinov/prj/dde/dde/XlTable.cpp",
     "misc/alioshinov/prj/dde/dde/XlTable.h",
     "misc/alioshinov/prj/dde/dde/XlTable_test.cpp",
     "misc/alioshinov/prj/dde/dde/command_line_parser.cpp",
     "misc/alioshinov/prj/dde/dde/command_line_parser.h",
     "misc/alioshinov/prj/dde/dde/command_line_parser_test.cpp",
     "misc/alioshinov/prj/dde/dde/dde.vcproj",
     "misc/alioshinov/prj/dde/dde/dde.vcproj.HASTER.Alioshinov.user",
     "misc/alioshinov/prj/dde/dde/dde.vcproj.NOTEBOOK.Haster.user",
     "misc/alioshinov/prj/dde/dde/dde_server.cpp",
     "misc/alioshinov/prj/dde/dde/dde_server.h",
     "misc/alioshinov/prj/dde/dde/dde_server_test.cpp",
     "misc/alioshinov/prj/dde/dde/main.cpp",
     "misc/alioshinov/prj/dde/dde_test.ncb",
     "misc/alioshinov/prj/dde/dde_test.sln",
     "misc/alioshinov/prj/dde/dde_test.suo",
     "misc/alioshinov/prj/dde/gtestd.lib",
     "misc/alioshinov/prj/dde/~$E_server.doc",
     "misc/okis/ANALYS.vbs",
     "misc/okis/ANALYS.wsc",
     "misc/okis/CSV2SQL.vbs",
     "misc/okis/DDE.vbs",
     "misc/okis/DDE.wsc",
     "misc/okis/FindHTA68.exe",
     "misc/okis/GearBox.qpl",
     "misc/okis/GearBox.wsc",
     "misc/okis/JET40.reg",
     "misc/okis/LOG.hta",
     "misc/okis/ML_EXAMPLE.vbs",
     "misc/okis/OLD/ANALYS.vbs",
     "misc/okis/OLD/ANALYS.wsc",
     "misc/okis/OLD/CSV2SQL.vbs",
     "misc/okis/OLD/DDE.vbs",
     "misc/okis/OLD/DDE.wsc",
     "misc/okis/OLD/FindHTA68.exe",
     "misc/okis/OLD/GearBox.qpl",
     "misc/okis/OLD/GearBox.wsc",
     "misc/okis/OLD/JET40.reg",
     "misc/okis/OLD/LOG.hta",
     "misc/okis/OLD/ML_EXAMPLE.vbs",
     "misc/okis/OLD/QUIK.UDL",
     "misc/okis/OLD/QUIK.mdb",
     "misc/okis/OLD/START.vbs",
     "misc/okis/OLD/TEST.vbs",
     "misc/okis/OLD/dde.exe",
     "misc/okis/OLD/dde2Console.vbs",
     "misc/okis/OLD/exit.exe",
     "misc/okis/OLD/quik.vbs",
     "misc/okis/OLD/testing.vbs",
     "misc/okis/OLD/\xC1\xFB\xF1\xF2\xF0\xFB\xE9\xD1\xF2\xE0\xF0\xF2.vbs",
     "misc/okis/OLD/\xF0\xE8\xE4\xEC\xE8.rtf",
     "misc/okis/OLD/\xF0\xE8\xE4\xEC\xE8.txt",
     "misc/okis/QUIK.UDL",
     "misc/okis/QUIK.mdb",
     "misc/okis/SERVER_INI.zip",
     "misc/okis/START.vbs",
     "misc/okis/TEST.vbs",
     "misc/okis/TRv01.zip",
     "misc/okis/dde.exe",
     "misc/okis/dde2Console.vbs",
     "misc/okis/exit.exe",
     "misc/okis/quik.vbs",
     "misc/okis/testing.vbs",
     "misc/okis/\xC1\xFB\xF1\xF2\xF0\xFB\xE9\xD1\xF2\xE0\xF0\xF2.vbs",
     "misc/okis/\xF0\xE8\xE4\xEC\xE8.rtf",
     "misc/okis/\xF0\xE8\xE4\xEC\xE8.txt",
     "misc/starting_dde.txt",
     "spec/dde/app_spec.rb",
     "spec/dde/client_spec.rb",
     "spec/dde/dde_string_spec.rb",
     "spec/dde/monitor_spec.rb",
     "spec/dde/server_shared.rb",
     "spec/dde/server_spec.rb",
     "spec/dde/xl_server_spec.rb",
     "spec/dde/xl_table_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/arvicco/dde}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{DDE server for Ruby}
  s.test_files = [
    "spec/dde/app_spec.rb",
     "spec/dde/client_spec.rb",
     "spec/dde/dde_string_spec.rb",
     "spec/dde/monitor_spec.rb",
     "spec/dde/server_shared.rb",
     "spec/dde/server_spec.rb",
     "spec/dde/xl_server_spec.rb",
     "spec/dde/xl_table_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<win_gui>, [">= 0.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<win_gui>, [">= 0.1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<win_gui>, [">= 0.1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

